### ISSUE TITLE
[Feature Request] Support Alternative Domains

### ISSUE THREAD

**Issue by as280093** [Kinuseka/GoGo-Downloader#2]
as `Gogoanime.so` is blocked in many countries it could be great to implement other domains, as they are the same as the main domain.

Here is the list of all domains Gogoanime supports officially 
```
╔═══════════════════════════════════╗
║          Active Domains           ║
╠═════════════════╦═════════════════╣
║ gogoanime.so    ║ gogoanime.vc    ║
╠═════════════════╩═════════════════╣
║        Redirecting Domains        ║
╠═════════════════╦═════════════════╣
║ gogoanime.sh    ║ gogoanime.tv    ║
║ gogoanime.io    ║ gogoanime.in    ║
║ gogoanime.movie ║ gogoanime.video ║
║ gogoanime.co    ║                 ║
╚═════════════════╩═════════════════╝
```
something similar to `quality` interchangable

**Comment by Kinuseka** [comment]
Are the redirecting domains necessary? They seem to redirect to the same **gogoanime.so** or **gogoanime.vc**, is there any **significant difference?** Would also love to know what **country** is gogoanime.so is blocked in

**Comment by as280093** [comment]
All i know is `gogoanime.so` is blocked in india but `gogoanime.vc` works here

**Comment by Kinuseka** [comment]
Added on V1.3 please update and try it out

**Comment by as280093** [comment]
works fine
